[package]
name = "frc_2025_arm_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.2", default-features = false, features = ["bevy_core_pipeline", "bevy_window", "bevy_winit"] }
bevy_rapier2d = "0.28.0"
