name: Rust Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            pkg-config \
            libudev-dev
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build Release
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: linux
            packages: libasound2-dev pkg-config libudev-dev
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: macos
            packages: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows
            packages: ''
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.packages }}
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get binary name
        id: get-binary-name
        shell: bash
        run: |
          BINARY_NAME=$(grep '^name = ' Cargo.toml | head -n1 | cut -d'"' -f2)
          echo "Binary name is: $BINARY_NAME"
          echo "name=$BINARY_NAME" >> $GITHUB_OUTPUT
      
      - name: Build release
        run: cargo build --verbose --release --target ${{ matrix.target }}
      
      - name: Set binary path
        id: binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            echo "path=target/${{ matrix.target }}/release/${{ steps.get-binary-name.outputs.name }}.exe" >> $GITHUB_OUTPUT
          else
            echo "path=target/${{ matrix.target }}/release/${{ steps.get-binary-name.outputs.name }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.artifact_name }}
          path: ${{ steps.binary.outputs.path }}
          if-no-files-found: error

  combine-artifacts:
    name: Combine Artifacts
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Combine artifacts
        run: |
          mkdir -p combined
          cp -r artifacts/*/* combined/
      
      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: combined
          if-no-files-found: error
